version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/Laravel/myproject"
    schedule:
      interval: "weekly"   # Options: daily, weekly, monthly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "php"  # Ignore specific dependencies if necessary
